# Dockerfile.frontend
FROM node:20 AS build

WORKDIR /app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos dependencias ignorando el conflicto de versiones de sweetalert con Angular 21
RUN npm install --legacy-peer-deps

# Copiamos el resto del código
COPY . .

# Construimos la aplicación de Angular
RUN npm run build

# Etapa de producción
FROM nginx:latest

# El archivo nginx.conf ahora se monta mediante un volumen en el docker-compose.yml

# Copiamos los archivos construidos desde la etapa anterior
# En Angular 17+, el builder application genera la salida en dist/Dental-One/browser
COPY --from=build /app/dist/Dental-One/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
